#!/usr/bin/python
from picamera.array import PiRGBArray
from picamera import PiCamera

import socket
import cv2
import numpy
import time

#TCP_IP = 'localhost'
TCP_IP = '192.168.0.106'
TCP_PORT = 5001
CALIDAD = 100
RESOLUCION = (600,600)

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
direccion = (TCP_IP,TCP_PORT)

#capture = cv2.VideoCapture(0)
camera = PiCamera()
camera.resolution = RESOLUCION
camera.rotation = 180
camera.framerate = 30
rawCapture = PiRGBArray(camera, size = RESOLUCION)

time.sleep(0.1)

try:
	for frame in camera.capture_continuous(rawCapture, format="bgr", use_video_port=True):

		inicio = time.time()

		frame = frame.array

		encode_param=[int(cv2.IMWRITE_JPEG_QUALITY),CALIDAD]
		result, imgencode = cv2.imencode('.jpg', frame, encode_param)
		data = numpy.array(imgencode)
		stringData = data.tostring()

		
		sock.sendto( stringData, direccion );
		
		decimg=cv2.imdecode(data,1)

		'''cv2.imshow('CLIENT',decimg)

		k = cv2.waitKey(1) & 0xFF
		if k == 27:
			break
		'''

		fin = time.time()

		print('Tiempo: ' + str(fin - inicio))

		rawCapture.truncate(0)

except:
	raise

finally:
	sock.close()
	cv2.destroyAllWindows()